- .travis.yml
- README.md
> #22 travis integration

- Singularity/Singularity/Game1.cs
- Singularity/Singularity/Libraries/Primitives2D.cs
- Singularity/Singularity/Singularity.csproj
- Singularity/Singularity/platform/Road.cs
Road class has been completed but still requires integration with the map.
Closes #50
> #50 create roads

- Singularity/Singularity/Game1.cs
- Singularity/Singularity/Units/IUnit.cs
- Singularity/Singularity/Units/MilitaryUnit.cs
> #51 military sprite movement

- Singularity/Singularity/Units/GeneralUnit.cs
- Changed EResourceType.None to EResourceType.Trash
> Fixed GeneralUnit compiling error

- Singularity/Singularity/Game1.cs
- Singularity/Singularity/Input/IKeyListener.cs
- Singularity/Singularity/Input/IMouseListener.cs
- Singularity/Singularity/Input/IMouseWheelListener.cs
- Singularity/Singularity/Input/InputManager.cs
- Singularity/Singularity/Input/KeyEvent.cs
- Singularity/Singularity/Input/MouseAction.cs
- Singularity/Singularity/Input/MouseEvent.cs
The InputManager should be ready for use
> fixed the InputManager. closes #115

- Singularity/Singularity/Screen/Slider.cs
- Singularity/Singularity/Screen/WindowItem.cs
- Singularity/Singularity/Singularity.csproj
slider class is implemented, has delegate which allows slider moving event to be sent out as well as decimal of how far along the slider bar the slider has been moved
> finished slider class

- Singularity/Singularity/Screen/Button.cs
fixed scaling issue for buttons
> small fixes to the button scaling function

- Singularity/Singularity/Screen/WindowObject.cs
- Singularity/Singularity/Singularity.csproj
- fix window movement + maximization
- remove console opening
- fix mouse click giveThrough
> close #211 close #210

- Singularity/Singularity/Platform/PlatformBlank.cs
> Buildings are now transparent while they are blueprints

- Singularity/Singularity/Screen/WindowObject.cs
fixed the bug that the input wasn't given through if the window was minimized
> close #229 window minimized input fix

- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Manager/DistributionManager.cs
- Singularity/Singularity/Map/Map.cs
- Singularity/Singularity/Platform/PlatformBlank.cs
- Singularity/Singularity/Resources/Resource.cs
- Singularity/Singularity/Units/GeneralUnit.cs
- Singularity/Singularity/Units/Task.cs
Bugfix pr. It seems, that during merging there occured multiple errors, resulting in a broken DistributionManager. 
Also fixed a bug where the producing units were wiggling (in a bad way). I noticed it just now, because on the old branch, there werent the updated draws of the platforms, so the Units vanished behind the platforms. 
I just want to push that fixes on master.
Also has: The NewlyDistribute method, a method that distributes the units fairly, after adding a new platform.
Please do NOT delete this branch!
> #225 finish the distribution manager

- Singularity/Singularity/Units/MilitaryPathfinder.cs
Using an implementation of Bresenham's algorithm to find "pixels" to be shaded for a straight line, the new implementation checks for walkability of grid positions in a straight line between the start and end position.
closes #244
> Implemented ability to find direct path in cases where there is no obstacle

- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Libraries/Primitives2D.cs
- Singularity/Singularity/Manager/MilitaryManager.cs
- Singularity/Singularity/Screen/ScreenClasses/GameScreen.cs
- Singularity/Singularity/Screen/Slider.cs
- Singularity/Singularity/Singularity.csproj
- Singularity/Singularity/Units/MilitaryUnit.cs
- Singularity/Singularity/Units/SelectionBox.cs
- Singularity/Singularity/Units/Settler.cs
- adds settler to game screen and transforms into CC if selected nonmoving and b key is pressed
- some selection box work done (everything is commented out though) decided to make a new branch for that
> #232 implement settler

- Singularity/Singularity/Platform/PlatformBlank.cs
Fixed the wrong platform color being used for barracks and the command center
Closes #253
> Fixed wrong platform showing for barracks and command center

- Singularity/Singularity/Game1.cs
- Singularity/Singularity/Screen/InfoBarWindowObject.cs
- Singularity/Singularity/Screen/InfoBoxWindow.cs
- Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
- Singularity/Singularity/Singularity.csproj
Started implementing the infoBar..
It's not fully implemented yet (missing civilUnits, rawRessources, refinedRessources + updates of the missionTime)
The PauseButton is implemented, so it can be used to update this quick implementation of the pauseMenuScreen + all Screens which can be opened from the pauseMenu.
> closes #240 implement the info bar

- Singularity/Singularity/Screen/Slider.cs
- one of the variables was named mLastPage and mLastPages. Renamed variables to avoid confusion and with that also the bug issue :)
> fixed small bug for sliders

- Singularity/Singularity/Manager/StoryManager.cs
- Singularity/Singularity/Screen/InfoBarWindowObject.cs
- Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/StatisticsScreen.cs
please review and approve my stats screen
closes #216
> closes #216 statistics screen

- Singularity/Singularity/Units/MilitaryUnit.cs
Fixed glow layer being below resources
> yvan674-glow-layer-fix

- Singularity/Singularity.sln
- Singularity/Singularity/Manager/DistributionDirector.cs
- Singularity/Singularity/Manager/DistributionManager.cs
- Singularity/Singularity/Map/StructureMap.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
- Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
- Singularity/Singularity/Screen/Slider.cs
- Singularity/Singularity/Screen/SliderHandler.cs
- Singularity/Singularity/Units/GeneralUnit.cs
- Singularity/Singularity/Units/Settler.cs
- Made the distributions manager multi graph functionality be incorporated in the game. 
- Readded the settlers "build commando center" to work again, since the game doesn't crash anymore
- Temporarily fixed the "laser tower defense placement" crash, which might create some issues with the slider adjustment
> Check comment for additions. 

- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Nature/Puddle.cs
- Singularity/Singularity/Nature/Rock.cs
- Singularity/Singularity/Units/EnemyUnit.cs
- Singularity/Singularity/Units/MilitaryUnit.cs
- made the military shooting the laser in the correct layer so its not covered by resources
- added a larger default puddle (small puddle still available)
- made the random generator for rocks better so that the rock structures look different
> minor fixes

- Singularity/Singularity/Property/ICollider.cs
- Singularity/Singularity/Utils/IdGenerator.cs
Changed IId to conform to standard naming scheme and made ICollider implement IId. Added documentation.
> Refactor IId

- Singularity/Singularity/Game1.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
- Singularity/Singularity/Platforms/StructurePlacer.cs
- Singularity/Singularity/Screen/ScreenClasses/MainMenuScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
- when specialized platform dies the blank platform is displaced
- if an enemy specialized platform dies the blank platform converts back into friendly
- added the map to structure placement in order to eventually prevent plats from being placed on collidables
> small bug fixes

- Singularity/Singularity/Levels/Achievements.cs
- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Manager/StoryManager.cs
- Singularity/Singularity/Map/Map.cs
- Singularity/Singularity/Map/ResourceMap.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
- Singularity/Singularity/Resources/MapResource.cs
- Singularity/Singularity/Resources/Resource.cs
- Singularity/Singularity/Resources/ResourceHelper.cs
- Singularity/Singularity/Screen/EScreen.cs
- Singularity/Singularity/Screen/InfoBarWindowObject.cs
- Singularity/Singularity/Screen/ScreenClasses/GamePauseManagerScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/StatisticsScreen.cs
- Singularity/Singularity/Singularity.csproj
- Singularity/Singularity/Units/MilitaryFast.cs
- Singularity/Singularity/Units/MilitaryHeavy.cs
- Singularity/Singularity/Units/MilitaryUnit.cs
please review. Not finished with everything but this version works. New Pause Menu (transitionable menu) and most of the stats tracking is in here.
> Norbert sprint12

- Singularity/Singularity/Manager/MilitaryManager.cs
Unit count should be fixed now as it just gets the count of friendly + hostile units
> Fixed unit count issue

- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Manager/DistributionDirector.cs
- Singularity/Singularity/Manager/DistributionManager.cs
- Singularity/Singularity/Map/ResourceMap.cs
- Singularity/Singularity/PlatformActions/MakeUnit.cs
- Singularity/Singularity/PlatformActions/ProduceResource.cs
- Singularity/Singularity/PlatformActions/RefineResourceAction.cs
- Singularity/Singularity/Platforms/Barracks.cs
- Singularity/Singularity/Platforms/CommandCenter.cs
- Singularity/Singularity/Platforms/Factory.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
- Singularity/Singularity/Resources/ResourceHelper.cs
- Singularity/Singularity/Screen/PlatformActionIWindowItem.cs
- Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
- Singularity/Singularity/Screen/UserInterfaceController.cs
- Singularity/Singularity/Singularity.csproj
- Singularity/Singularity/Units/Settler.cs
Factory is fully implemented. Some bugs are still there though, but quite distributed. On it.
> closes #82 factory

- Singularity/Singularity.sln
- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Manager/MilitaryManager.cs
- Singularity/Singularity/Map/UnitMap.cs
- Singularity/Singularity/Units/EnemyFast.cs
- Singularity/Singularity/Units/EnemyHeavy.cs
- Singularity/Singularity/Units/MilitaryFast.cs
- Singularity/Singularity/Units/MilitaryHeavy.cs
- Singularity/Singularity/Units/Native.cs
Non military units (i.e. settlers) would not be updated on the unit map.
> Fixed issue where the unitmap would not update for non military units

- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Map/Map.cs
- Singularity/Singularity/Map/ResourceMap.cs
- Singularity/Singularity/PlatformActions/RefineResourceAction.cs
- Singularity/Singularity/Platforms/Mine.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
- Singularity/Singularity/Platforms/Quarry.cs
- Singularity/Singularity/Platforms/Well.cs
- Singularity/Singularity/Resources/MapResource.cs
- Singularity/Singularity/Resources/Resource.cs
- Singularity/Singularity/Screen/ScreenClasses/GamePauseManagerScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/GamePauseScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/SaveGameScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/StatisticsScreen.cs
- Singularity/Singularity/Units/FreeMovingUnit.cs
- Singularity/Singularity/Units/GeneralUnit.cs
and stats tracking, please review.
Fixed a minor issue with production running while platforms are inactive
added stats tracking for everything
added save screen, not functional, yet.
> Norbert save screen and production

- Singularity/Singularity/AI/BasicAi.cs
- Singularity/Singularity/AI/Behavior/SimpleAiBehavior.cs
- Singularity/Singularity/Levels/Skirmish.cs
The game is won as soon as every command center of the enemy is destroyed. Currently nothing happens except for the game pausing and the WinScreen to be on the top of the stack
> Implemented the Win for the game. 

- Singularity/Singularity/Levels/Skirmish.cs
- Singularity/Singularity/Map/StructureMap.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
The game is lost by losing all command centers. Currently only pauses the game, the win screen doesn't draw anything.
> Made the game loseable

- Singularity/Singularity/Screen/ScreenClasses/DebugScreen.cs
> Made the enemy difficulty show in the debug screen

- Singularity/Singularity/Screen/ScreenClasses/UserInterfaceScreen.cs
- Singularity/Singularity/Units/FreeMovingUnit.cs
> Fixserializingagain

- Singularity/Singularity/AI/Behavior/AdvancedAiBehavior.cs
Made the AI move its defensive units if not active and made it NOT expand if not active
> Slight AI changes

- Singularity/Singularity/Content/LibSans14.spritefont
- Singularity/Singularity/Screen/ScreenClasses/GameModeSelectScreen.cs
- Singularity/Singularity/Screen/ScreenClasses/LoadGameManagerScreen.cs
Added possibility of future DLC to add a campaign
> Added the campaign flavor text

- Singularity/Singularity/AI/Behavior/AdvancedAiBehavior.cs
- Singularity/Singularity/Manager/MilitaryManager.cs
- Singularity/Singularity/Units/AFlocking.cs
- Singularity/Singularity/Units/FlockingGroup.cs
- Singularity/Singularity/Units/FreeMovingUnit.cs
> Made sure flockinggroups relaod content method is called

- Singularity/Singularity/Manager/DistributionManager.cs
- Singularity/Singularity/Singularity.csproj
- Singularity/Singularity/Units/GeneralUnit.cs
DONT CLOSE THIS BRANCH
I will further use it.
blabla see commits for chagnes.
> I think I fixed the bug with the multiple blueprints.

- Singularity/Singularity/Manager/DistributionManager.cs
- Singularity/Singularity/Platforms/PlatformBlank.cs
> Now Deleting platforms also deletes them from the CollisionMap

- Singularity/Singularity/Nature/Puddle.cs
- Singularity/Singularity/Nature/Rock.cs
- Singularity/Singularity/Units/MilitaryUnit.cs
> Leos improvements
